[package]
name = "common-settings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-ast = { path = "../ast" }
common-config = { path = "../config" }
common-exception = { path = "../../common/exception" }
common-meta-app = { path = "../../meta/app" }
common-meta-types = { path = "../../meta/types" }
common-users = { path = "../users" }
serde = { workspace = true }

async-backtrace = { workspace = true }
dashmap = "5.4"
itertools = "0.10.5"
log = { workspace = true }
num_cpus = "1.13.1"
once_cell = { workspace = true }
sys-info = "0.9"
