[package]
name = "common-proto-conv"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
common-expression = { path = "../../query/expression" }
common-meta-app = { path = "../app" }
common-protos = { path = "../protos" }

chrono = { workspace = true }
chrono-tz = { workspace = true, features = ["serde"] }
enumflags2 = { version = "0.7.7", features = ["serde"] }
minitrace = { workspace = true }
num = "0.4.0"
thiserror = { workspace = true }

[build-dependencies]

[dev-dependencies]
anyhow = { workspace = true }
convert_case = { version = "0.6.0" }
maplit = "1.0.2"
pretty_assertions = "1.3.0"
