[package]
name = "common-openai"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
common-exception = { path = "../exception" }
common-metrics = { path = "../metrics" }

# GitHub dependencies

# Crates.io dependencies
log = { workspace = true }
openai_api_rust = { git = "https://github.com/datafuse-extras/openai-api", rev = "819a0ed" }

[dev-dependencies]
