[package]
name = "common-storage"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[features]
storage-hdfs = ["common-meta-app/storage-hdfs"]

[dependencies]
common-arrow = { path = "../arrow" }
common-auth = { path = "../auth" }
common-base = { path = "../base" }
common-exception = { path = "../exception" }
common-expression = { path = "../../query/expression" }
common-meta-app = { path = "../../meta/app" }
storage-encryption = { path = "../../query/ee_features/storage_encryption" }

anyhow = { workspace = true }
arrow-schema = { workspace = true }
async-backtrace = { workspace = true }
async-trait = "0.1"
bytes = { workspace = true }
chrono = { workspace = true }
dashmap = { version = "5.5.1", features = ["serde"] }
flagset = "0.4"
futures = "0.3"
log = { workspace = true }
metrics = "0.20.1"
opendal = { workspace = true }
ordered-float = { workspace = true }
parquet = { workspace = true }
regex = "1.8.1"
reqwest = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
