[package]
name = "common-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = true

[features]
default = []
storage-hdfs = ["common-storage/storage-hdfs"]

[package.metadata.cargo-machete]
ignored = ["strum"]

[dependencies]
chrono-tz = { workspace = true }
common-base = { path = "../../common/base" }
common-exception = { path = "../../common/exception" }
common-grpc = { path = "../../common/grpc" }
common-meta-app = { path = "../../meta/app" }
common-storage = { path = "../../common/storage" }
common-tracing = { path = "../../common/tracing" }
common-users = { path = "../users" }

clap = { workspace = true }
hex = "0.4.3"
log = { workspace = true }
once_cell = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serfig = "0.1.0"
strum = "0.24.1"

[dev-dependencies]
pretty_assertions = "1.3.0"

[build-dependencies]
common-building = { path = "../../common/building" }
