name: "Upload failure Artifacts"
description: "Upload failure Artifacts"
inputs:
  name:
    description: ""
    required: true
runs:
  using: "composite"
  steps:
    - name: pack failure artifacts
      shell: bash
      run: |
        killall -9 databend-query || true
        killall -9 databend-meta || true

        docker ps -a
        mkdir -p .databend/docker/
        docker ps -a --format "{{.Names}}" | while read -r line; do
            docker logs "$line" > .databend/docker/"$line".log
        done

        mkdir -p target
        find -type d -name .databend -print0 | xargs -0 tar -zcf target/failure-${{ inputs.name }}.tar.gz
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: target/failure-${{ inputs.name }}.tar.gz
