[package]
name = "common-meta-client"
description = "common meta grpc"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = true

[features]
enable-histogram = ["common-metrics/enable-histogram"]

[dependencies]
common-arrow = { path = "../../common/arrow" }
common-base = { path = "../../common/base" }
common-grpc = { path = "../../common/grpc" }
common-meta-api = { path = "../api" }
common-meta-kvapi = { path = "../kvapi" }
common-meta-types = { path = "../types" }
common-metrics = { path = "../../common/metrics" }
common-tracing = { path = "../../common/tracing" }

derive_more = { workspace = true }
futures = "0.3.24"
lazy_static = { workspace = true }
log = { workspace = true }
logcall = { workspace = true }
minitrace = { workspace = true }
once_cell = { workspace = true }
parking_lot = "0.12.1"
prost = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tonic = { workspace = true }

[dev-dependencies]
common-exception = { path = "../../common/exception" }
common-meta-app = { path = "../app" }

anyhow = { workspace = true }
rand = "0.8.5"

[build-dependencies]
common-building = { path = "../../common/building" }
