cargo-features = ["edition2021"]

[package]
name = "common-arrow"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[features]
simd = ["arrow/simd"]

[dependencies] # In alphabetical order
# Workspace dependencies

# Github dependencies
arrow = { package = "arrow2", git="https://github.com/datafuse-extras/arrow2", rev = "7765067" }
arrow-flight = { git="https://github.com/datafuse-extras/arrow2", rev = "7765067" }
#parquet2 = {package = "parquet2", git = "https://github.com/datafuse-extras/parquet2", rev = "d28330f"}
# Crates.io dependencies
parquet2 = { version = "0.3", optional = false, default_features = false, features = ["stream"] }

[dev-dependencies]