[package]
name = "common-grpc"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-base = { path = "../base" }
common-exception = { path = "../exception" }

# GitHub dependencies

# Crates.io dependencies
anyerror = { workspace = true }
hyper = "0.14.20"
jwt-simple = "0.11.0"
log = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }
trust-dns-resolver = { version = "0.22.0", features = ["system-config"] }

[build-dependencies]

[features]
mocks = []
