[workspace.package]
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[workspace]
resolver = "2"
members = [
    # Binaries
    "src/binaries",
    # Common
    "src/common/arrow",
    "src/common/auth",
    "src/common/base",
    "src/common/building",
    "src/common/cache",
    "src/common/cloud_control",
    "src/common/compress",
    "src/common/exception",
    "src/common/grpc",
    "src/common/hashtable",
    "src/common/http",
    "src/common/io",
    "src/common/metrics",
    "src/common/openai",
    "src/common/tracing",
    "src/common/storage",
    "src/common/vector",
    "src/common/license",
    # Query
    "src/query/ast",
    "src/query/codegen",
    "src/query/config",
    "src/query/constraint",
    "src/query/catalog",
    "src/query/sharing",
    "src/query/sharing_endpoint",
    "src/query/datavalues",
    "src/query/expression",
    "src/query/formats",
    "src/query/functions",
    "src/query/management",
    "src/query/pipeline/core",
    "src/query/pipeline/sinks",
    "src/query/pipeline/sources",
    "src/query/pipeline/transforms",
    "src/query/profile",
    "src/query/settings",
    "src/query/sql",
    "src/query/storages/common/blocks",
    "src/query/storages/common/cache",
    "src/query/storages/common/cache_manager",
    "src/query/storages/common/index",
    "src/query/storages/common/locks",
    "src/query/storages/common/pruner",
    "src/query/storages/common/table_meta",
    "src/query/storages/factory",
    "src/query/storages/fuse",
    "src/query/storages/hive/hive",
    "src/query/storages/iceberg",
    "src/query/storages/information_schema",
    "src/query/storages/memory",
    "src/query/storages/null",
    "src/query/storages/random",
    "src/query/storages/share",
    "src/query/storages/stage",
    "src/query/storages/system",
    "src/query/storages/view",
    "src/query/storages/parquet",
    "src/query/storages/result_cache",
    "src/query/users",
    "src/query/ee_features/vacuum_handler",
    "src/query/ee_features/background_service",
    "src/query/ee_features/aggregating_index",
    "src/query/ee_features/data_mask",
    "src/query/ee_features/storage_encryption",
    # databend-query
    "src/query/service",
    # enterprise
    "src/query/ee",
    # Meta
    "src/meta/api",
    "src/meta/app",
    "src/meta/embedded",
    "src/meta/kvapi",
    "src/meta/process",
    "src/meta/raft-store",
    "src/meta/sled-store",
    "src/meta/stoerr",
    "src/meta/store",
    "src/meta/types",
    "src/meta/ee",
    # meta proto
    "src/meta/proto-conv",
    "src/meta/protos",
    # databend-meta
    "src/meta/service",
    # sqllogictest
    "tests/sqllogictests",

    "src/bendpy",
    # sqlsmith
    "src/tests/sqlsmith",
]

[workspace.dependencies]
# databend maintains:
sled = { git = "https://github.com/datafuse-extras/sled", tag = "v0.34.7-datafuse.1", default-features = false }
opendal = { version = "0.42", features = [
    "layers-minitrace",
    "layers-prometheus-client",
    "services-ipfs",
    "services-moka",
    "trust-dns",
] }
ethnum = { version = "1.3.2" }
ordered-float = { version = "3.6.0", default-features = false }
jsonb = { git = "https://github.com/datafuselabs/jsonb", rev = "1d7a3e9" }

# openraft = { version = "0.8.2", features = ["compat-07"] }
# For debugging
openraft = { git = "https://github.com/drmingdrmer/openraft", tag = "v0.8.4-alpha.10", features = [
    "compat-07",
    "tracing-log",
    # allows to remove all data from a follower and restore from the leader.
    "loosen-follower-log-revert",
] }

# type helper
derive_more = "0.99.17"
itertools = "0.10.5"
lazy_static = "1.4.0"
once_cell = "1.15.0"

# future and async
futures = "0.3.24"
futures-util = "0.3.24"
futures-async-stream = { version = "0.2.7" }
stream-more = "0.1.3"
bytes = "1.5.0"

# error
anyhow = { version = "1.0.65" }
anyerror = { version = "=0.1.10" }
thiserror = { version = "1" }

# versioning
semver = "1.0.14"

# CLI
clap = { version = "4.4.2", features = ["derive"] }

# server
tonic = { version = "0.10.2", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }
tonic-reflection = { version = "0.10.2" }

# Crates from arrow-rs
arrow = { version = "47.0.0", features = ["pyarrow"] }
arrow-select = { version = "47.0.0" }
arrow-array = { version = "47.0.0" }
arrow-buffer = { version = "47.0.0" }
arrow-data = { version = "47.0.0" }
arrow-flight = { version = "47.0.0", features = ["flight-sql-experimental", "tls"] }
arrow-ipc = { version = "47.0.0" }
arrow-schema = { version = "47.0.0", features = ["serde"] }
arrow-ord = { version = "47.0.0" }
arrow-cast = { version = "47.0.0", features = ["prettyprint"] }
parquet = { version = "47.0.0", features = ["async"] }
parquet_rs = { package = "parquet", version = "47.0.0" }
arrow-format = { version = "0.8.1", features = ["flight-data", "flight-service", "ipc"] }

# serialization
prost = { version = "0.12.1" }
prost-build = { version = "0.12.1" }
serde = { version = "1.0.164", features = ["derive", "rc"] }
serde_json = { version = "1.0.85", default-features = false, features = ["preserve_order"] }
tonic-build = { version = "0.10.2" }

# chrono
chrono = { version = "0.4.31", features = ["serde"] }
chrono-tz = { version = "0.8", features = ["serde"] }

# memory
bumpalo = "3.12.0"
tikv-jemalloc-ctl = { version = "0.5.0", features = ["use_std"] }

# http
reqwest = { version = "0.11.19", default-features = false, features = [
    "json",
    "rustls-tls",
    "rustls-tls-native-roots",
    "trust-dns",
] }

# runtime
tokio = { version = "1.26.0", features = ["full"] }

# backtrace
async-backtrace = { git = "https://github.com/zhang2014/async-backtrace.git", rev = "e7e1b5f" }

# observability
logcall = "0.1.5"
log = { version = "0.4.19", features = ["serde", "kv_unstable_std"] }
minitrace = { version = "0.6", features = ["enable"] }
prometheus-client = "0.21.2"

# test
mysql_async = { version = "0.33", default-features = false, features = ["rustls-tls"] }

[profile.release]
debug = 1
lto = "thin"
overflow-checks = false
incremental = false
opt-level = "s"
# codegen-units = 1       # Reduce number of codegen units to increase optimizations.

# [profile.release.package]
# arrow2 = { codegen-units = 4 }
# common-functions = { codegen-units = 16 }
# databend-query = { codegen-units = 4 }
# databend-binaries = { codegen-units = 4 }

[profile.bench]
debug = true
overflow-checks = false

[profile.dev]
split-debuginfo = "unpacked"
overflow-checks = false
# wait until https://github.com/rust-lang/rust/issues/100142 fixed
incremental = false

[profile.dev.package]
addr2line = { opt-level = 3 }
adler = { opt-level = 3 }
gimli = { opt-level = 3 }
miniz_oxide = { opt-level = 3 }
object = { opt-level = 3 }
rustc-demangle = { opt-level = 3 }

[profile.test]
opt-level = 0
debug = true
codegen-units = 16
lto = false
debug-assertions = true
overflow-checks = true
rpath = false

[patch.crates-io]
# If there are dependencies that need patching, they can be listed below.
arrow-format = { git = "https://github.com/everpcpc/arrow-format", rev = "588d371" }
parquet2 = { git = "https://github.com/jorgecarleitao/parquet2", rev = "b0e6545" }
metrics = { git = "https://github.com/datafuse-extras/metrics.git", rev = "fc2ecd1" }
icelake = { git = "https://github.com/icelake-io/icelake", rev = "f06cdf3" }
sentry = { git = "https://github.com/getsentry/sentry-rust", rev = "6ef6d97" }
