[package]
name = "databend-common-management"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[dependencies]
databend-common-base = { path = "../../common/base" }
databend-common-exception = { path = "../../common/exception" }
databend-common-functions = { path = "../functions" }
databend-common-meta-api = { path = "../../meta/api" }
databend-common-meta-app = { path = "../../meta/app" }
databend-common-meta-kvapi = { path = "../../meta/kvapi" }
databend-common-meta-store = { path = "../../meta/store" }
databend-common-meta-types = { path = "../../meta/types" }
databend-common-proto-conv = { path = "../../meta/proto-conv" }
databend-common-protos = { path = "../../meta/protos" }

async-backtrace = { workspace = true }
async-trait = { workspace = true }
minitrace = { workspace = true }
serde_json = { workspace = true }
log = "0.4.19"

[dev-dependencies]
databend-common-expression = { path = "../../query/expression" }
databend-common-meta-embedded = { path = "../../meta/embedded" }
databend-common-storage = { path = "../../common/storage" }
mockall = "0.11.2"
