[build-system]
requires = ["maturin>1.1.0"]
build-backend = "maturin"

[project]
name = "databend"
requires-python = ">=3.7"
description = "Databend Python Binding"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[project.optional-dependencies]
benchmark = []
docs = ["pdoc"]
test = ["pytest", "pandas", "polars"]

[project.urls]
Documentation = "https://databend.rs"
Homepage =  "https://databend.rs"
"Home-page" =  "https://databend.rs"
Repository = "https://github.com/datafuselabs/databend"

[tool.maturin]
features = ["pyo3/extension-module"]
