[package]
name = "common-meta-api"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = true

[dependencies]
common-exception = { path = "../../common/exception" }
common-expression = { path = "../../query/expression" }
common-meta-app = { path = "../app" }
common-meta-kvapi = { path = "../kvapi" }
common-meta-stoerr = { path = "../stoerr" }
common-meta-types = { path = "../types" }
common-proto-conv = { path = "../proto-conv" }
common-protos = { path = "../protos" }

anyhow = { workspace = true }
async-trait = "0.1.57"
chrono = { workspace = true }
enumflags2 = { version = "0.7.7", features = ["serde"] }
log = { workspace = true }
logcall = { workspace = true }
maplit = "1.0.2"
minitrace = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }
