[package]
name = "common-sql"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
default = []
storage-hdfs = ["common-config/storage-hdfs"]
z3-prove = ["common-constraint"]

[dependencies] # In alphabetical order
# Workspace dependencies
common-ast = { path = "../ast" }
common-base = { path = "../../common/base" }
common-catalog = { path = "../catalog" }
common-config = { path = "../config" }
common-constraint = { path = "../constraint", optional = true }
common-exception = { path = "../../common/exception" }
common-expression = { path = "../expression" }
common-functions = { path = "../functions" }
common-license = { path = "../../common/license" }
common-meta-app = { path = "../../meta/app" }
common-meta-types = { path = "../../meta/types" }
common-metrics = { path = "../../common/metrics" }

common-pipeline-core = { path = "../pipeline/core" }
common-pipeline-sources = { path = "../pipeline/sources" }
common-pipeline-transforms = { path = "../pipeline/transforms" }

common-profile = { path = "../profile" }
common-settings = { path = "../settings" }
common-storage = { path = "../../common/storage" }
common-storages-parquet = { path = "../storages/parquet" }
common-storages-result-cache = { path = "../storages/result_cache" }
common-storages-stage = { path = "../storages/stage" }
common-storages-view = { path = "../storages/view" }
common-users = { path = "../users" }
data-mask-feature = { path = "../ee_features/data_mask" }
storages-common-table-meta = { path = "../storages/common/table_meta" }

# GitHub dependencies

# Crates.io dependencies
ahash = { version = "0.8.2", features = ["no-rng"] }
anyhow = { workspace = true }
async-backtrace = { workspace = true }
async-recursion = "1.0.0"
async-trait = { version = "0.1.57", package = "async-trait-fn" }
chrono = { workspace = true }
chrono-tz = { workspace = true }
cidr = { version = "0.2.2" }
cron = "0.12.0"
ctor = "0.1.26"
dashmap = "5.4"
educe = "0.4"
enum-as-inner = "0.5"
globiter = "0.1"
indexmap = "2.0.0"
itertools = "0.10.5"
log = { workspace = true }
minitrace = { workspace = true }
num-derive = "0.3.3"
num-traits = "0.2.15"
once_cell = { workspace = true }
opendal = { workspace = true }
ordered-float = { workspace = true }
parking_lot = "0.12.1"
percent-encoding = "2"
regex = "1.8.1"
roaring = "0.10.1"
serde = { workspace = true }
simsearch = "0.2"
time = "0.3.14"
