[package]
name = "databend-meta"
description = "distributed meta data service"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[features]
default = ["simd"]
memory-profiling = ["common-base/memory-profiling", "common-http/memory-profiling"]
simd = ["common-arrow/simd"]
tokio-console = ["common-tracing/console", "common-base/tracing"]
io-uring = [
    "sled/io_uring",
    "common-meta-sled-store/io-uring",
    "common-meta-raft-store/io-uring",
]

enable-histogram = ["common-metrics/enable-histogram"]

[dependencies]
# Workspace dependencies
common-arrow = { path = "../../common/arrow" }
common-base = { path = "../../common/base" }
common-grpc = { path = "../../common/grpc" }
common-http = { path = "../../common/http" }
common-meta-api = { path = "../api" }
common-meta-client = { path = "../client" }
common-meta-kvapi = { path = "../kvapi" }
common-meta-raft-store = { path = "../raft-store" }
common-meta-sled-store = { path = "../sled-store" }
common-meta-stoerr = { path = "../stoerr" }
common-meta-types = { path = "../types" }
common-metrics = { path = "../../common/metrics" }
common-tracing = { path = "../../common/tracing" }

# GitHub dependencies
sled = { workspace = true }

# Crates.io dependencies
anyerror = { workspace = true }
anyhow = { workspace = true }
async-trait = "0.1.57"
backon = "0.4"
clap = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
futures-async-stream = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
logcall = { workspace = true }
maplit = "1.0.2"
minitrace = { workspace = true }
once_cell = { workspace = true }
poem = { version = "~1.3.57", features = ["rustls"] }
prometheus-client = "0.21.2"
prost = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serfig = "0.1.0"
tokio-stream = "0.1.10"
tonic = { workspace = true }
tonic-reflection = { workspace = true }

[dev-dependencies]
env_logger = "0.10.0"
maplit = "1.0.2"
pretty_assertions = "1.3.0"
regex = "1.8.1"
reqwest = { workspace = true }
temp-env = "0.3.0"
tempfile = "3.4.0"
test-harness = "0.1.1"

[build-dependencies]
common-building = { path = "../../common/building" }
