[package]
name = "databend-common-meta-store"
description = "MetaStore is impl with either a local embedded meta store, or a grpc-client of metasrv"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[features]
io-uring = ["databend-common-meta-embedded/io-uring"]

[dependencies]
# Workspace dependencies
databend-common-grpc = { path = "../../common/grpc" }
databend-common-meta-client = { path = "../client" }
databend-common-meta-embedded = { path = "../embedded" }
databend-common-meta-kvapi = { path = "../kvapi" }
databend-common-meta-types = { path = "../types" }

# Crates.io dependencies
async-trait = { workspace = true }
etcd-rs = "1.0.1"
log = { workspace = true }
tokio-stream = { workspace = true }
