[package]
name = "common-storages-fuse"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-arrow = { path = "../../../common/arrow" }
common-base = { path = "../../../common/base" }
common-cache = { path = "../../../common/cache" }
common-catalog = { path = "../../catalog" }
common-exception = { path = "../../../common/exception" }
common-expression = { path = "../../expression" }
common-functions = { path = "../../functions" }
common-io = { path = "../../../common/io" }
common-meta-app = { path = "../../../meta/app" }
common-meta-types = { path = "../../../meta/types" }
common-metrics = { path = "../../../common/metrics" }
common-pipeline-core = { path = "../../pipeline/core" }
common-pipeline-sinks = { path = "../../pipeline/sinks" }
common-pipeline-sources = { path = "../../pipeline/sources" }
common-pipeline-transforms = { path = "../../pipeline/transforms" }
common-sharing = { path = "../../sharing" }
common-sql = { path = "../../sql" }
common-storage = { path = "../../../common/storage" }
jsonb = { workspace = true }

storages-common-blocks = { path = "../common/blocks" }
storages-common-cache = { path = "../common/cache" }
storages-common-cache-manager = { path = "../common/cache_manager" }
storages-common-index = { path = "../common/index" }
storages-common-locks = { path = "../common/locks" }
storages-common-pruner = { path = "../common/pruner" }
storages-common-table-meta = { path = "../common/table_meta" }

ahash = "0.8.3"
async-backtrace = { workspace = true }
async-trait = { version = "0.1.57", package = "async-trait-fn" }
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
bytes = { workspace = true }
chrono = { workspace = true }
enum-as-inner = "0.5"
futures = "0.3.24"
futures-util = { workspace = true }
indexmap = "2.0.0"
itertools = "0.10.5"
log = { workspace = true }
metrics = "0.20.1"
minitrace = { workspace = true }
opendal = { workspace = true }
parquet-format-safe = "0.2"
rand = "0.8.5"
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10.6"
siphasher = "0.3.10"
streaming-decompression = "0.1.2"
sys-info = "0.9"

typetag = "0.2.3"
uuid = { version = "1.1.2", features = ["serde", "v4"] }
