[package]
name = "common-metrics"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
enable-histogram = ["metrics/enable-histogram"]

[dependencies]
# Workspace dependencies
common-exception = { path = "../exception" }

# Crates.io dependencies
lazy_static = { workspace = true }
metrics = "0.20.1"
metrics-exporter-prometheus = { version = "0.11.0", default-features = false }
parking_lot = "0.12.1"
prometheus-client = { workspace = true }
prometheus-parse = "0.2.3"
serde = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
procfs = "0.15.1"

[dev-dependencies]
anyhow = { workspace = true }

[dev-dependencies.tokio]
default-features = false
features = ["io-util", "net", "sync", "rt-multi-thread", "macros"]
version = "1.26.0"
