cargo-features = ["edition2021"]

[package]
name = "datafuse-query"
version = "0.1.0"
description = "A real-time Cloud Distributed Query Engine"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[[bin]]
name = "datafuse-query"
path = "src/bin/datafuse-query.rs"

[[bin]]
name = "datafuse-benchmark"
path = "src/bin/datafuse-benchmark.rs"

[features]
default = ["simd"]
simd = ["common-arrow/simd"]

[dependencies]
# Workspace dependencies
common-arrow = { path = "../common/arrow" }
common-datablocks = { path = "../common/datablocks" }
common-datavalues = { path = "../common/datavalues" }
common-exception = { path = "../common/exception" }
common-flights = { path = "../common/flights" }
common-functions = { path = "../common/functions" }
common-infallible = { path = "../common/infallible" }
common-planners = { path = "../common/planners" }
common-progress = { path = "../common/progress" }
common-runtime = { path = "../common/runtime" }
common-streams = { path = "../common/streams" }
common-tracing = { path = "../common/tracing" }
common-profling = { path = "../common/profiling" }
common-store-api = { path = "../common/store-api" }
common-io = { path = "../common/io" }
common-metatypes = { path = "../common/metatypes" }
common-dal= {path = "../common/dal"}

# Github dependencies
msql-srv = { git = "https://github.com/datafuse-extras/msql-srv", rev = "cc53408" }
clickhouse-rs = { git = "https://github.com/datafuse-extras/clickhouse-rs", rev = "c4743a9" }
sqlparser = { git = "https://github.com/datafuse-extras/sqlparser-rs", rev = "2535347" }

# Crates.io dependencies
clickhouse-srv = "0.3.1"
bumpalo = "3.7.0"
ahash = "0.7.4"
async-trait = "0.1"
crossbeam = "0.8"
quantiles = "0.7.1"
ctrlc = { version = "3.1.9", features = ["termination"] }
crossbeam-queue = "0.3.2"
env_logger = "0.9"
futures = "0.3"
indexmap = "1.7.0"
lazy_static = "1.4.0"
log = "0.4"
metrics = "0.17.0"
metrics-exporter-prometheus = "0.6.0"
num = "0.4"
nom = "7.0.0"
num_cpus = "1.0"
paste = "^1.0"
pnet = "0.28.0"
chrono-tz = "0.5"
chrono =  "0.4.0"
prost = "0.8.0"
rand = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
structopt-toml = "0.5.0"
threadpool = "1.8.1"
tokio-stream = { version = "0.1", features = ["net"] }
toml = "0.5.6"
tonic = "0.5.2"
walkdir = "2.3.2"
warp = { version = "0.3.1", features = ["tls"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
lru = "0.6.6"
byteorder = "1"

[dev-dependencies]
pretty_assertions = "0.7"
criterion = "0.3"
mysql = "21.0.1"
reqwest = { version = "0.11", features = ["json"] }
flaky_test = "0.1"

[build-dependencies]
common-building = {path = "../common/building"}

[[bench]]
name = "bench_main"
harness = false
