[package]
name = "common-storages-share"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-exception = { path = "../../../common/exception" }
common-meta-app = { path = "../../../meta/app" }
common-storages-util = { path = "../util" }

opendal = { version = "0.14.1", features = ["layers-retry"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"

[dev-dependencies]
goldenfile = "1.4"
tempfile = "3.3.0"
