[package]
name = "common-catalog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-arrow = { path = "../../common/arrow" }
common-base = { path = "../../common/base" }
common-config = { path = "../config" }
common-exception = { path = "../../common/exception" }
common-expression = { path = "../expression" }
common-io = { path = "../../common/io" }
common-meta-api = { path = "../../meta/api" }
common-meta-app = { path = "../../meta/app" }
common-meta-store = { path = "../../meta/store" }
common-meta-types = { path = "../../meta/types" }
common-pipeline-core = { path = "../pipeline/core" }
common-settings = { path = "../settings" }
common-storage = { path = "../../common/storage" }
common-users = { path = "../users" }
storages-common-table-meta = { path = "../storages/common/table_meta" }

arrow-schema = { workspace = true }
async-backtrace = { workspace = true }
async-trait = "0.1.57"
chrono = { workspace = true }
dashmap = "5.4"
dyn-clone = "1.0.9"
parking_lot = "0.12"
parquet_rs = { workspace = true }
rand = "0.8.5"
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10.6"
thrift = "0.17.0"
typetag = "0.2.3"

[dev-dependencies]
goldenfile = "1.4"
