[package]
name = "common-pipeline-core"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-exception = { path = "../../../common/exception" }
common-expression = { path = "../../expression" }

async-backtrace = { workspace = true }
async-trait = "0.1.57"
futures = "0.3.24"
minitrace = { workspace = true }
petgraph = "0.6.2"

[dev-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
typetag = "0.2.3"
