[package]
name = "common-meta-embedded"
description = "distributed meta data service"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[features]
io-uring = ["common-meta-sled-store/io-uring", "common-meta-raft-store/io-uring"]

[dependencies]
# Workspace dependencies
common-base = { path = "../../common/base" }
common-meta-api = { path = "../api" }
common-meta-kvapi = { path = "../kvapi" }
common-meta-raft-store = { path = "../raft-store" }
common-meta-sled-store = { path = "../sled-store" }
common-meta-stoerr = { path = "../stoerr" }
common-meta-types = { path = "../types" }

# Crates.io dependencies
async-trait = "0.1.57"
log = { workspace = true }
minitrace = { workspace = true }
once_cell = { workspace = true }
tempfile = "3.4.0"

[dev-dependencies]
anyhow = { workspace = true }
