[package]
name = "common-tracing"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
console = ["console-subscriber", "tracing", "tracing-subscriber"]

[dependencies] # In alphabetical order
# Workspace dependencies
common-base = { path = "../base" }

# Crates.io dependencies
console-subscriber = { version = "0.2.0", optional = true }
defer = "0.1"
fern = "0.6.2"
humantime = "2.1.0"
log = { workspace = true }
minitrace = { workspace = true }
minitrace-opentelemetry = "0.6"
opentelemetry = { version = "0.20", features = ["trace"] }
opentelemetry-otlp = { version = "0.13", features = ["trace"] }
serde = { workspace = true }
serde_json = "1"
tonic = { workspace = true }
tracing = { version = "0.1.37", optional = true }
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json", "valuable"], optional = true }
