[package]
name = "common-meta-kvapi"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = true

[dependencies]
common-meta-types = { path = "../types" }

anyhow = { workspace = true }
async-trait = "0.1.57"
futures-util = { workspace = true }
log = { workspace = true }
minitrace = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
