name: Production

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "scripts/setup/**"
      - ".devcontainer/**"

jobs:
  linux:
    uses: ./.github/workflows/reuse.linux.yml
    secrets: inherit
    with:
      build_profile: release
      runner_provider: gcp

  macos:
    needs: linux
    uses: ./.github/workflows/reuse.macos.yml
    secrets: inherit
    with:
      build_profile: release
